* LOOPBACK
** Comprendre la validation des modeles
*** Empecher la modification de certains champs et la remplacer par un ajout auto
** Gerer les ACLs
** restreindre la visibilite des proprietes des modeles
** ajouter un hook avant l upload d une chanson pour la valider, l enregistrer en
filesystem et la linker au modele.

Packages:
* borewit/music-metadata for metadata retrieval





* TUsers
** Roles
*** Tourist
	everybody can sign in to chat and like etc...
*** Basic
	can upload tracks
*** Adherent
	can upload tracks and invite people
*** Mod
	can edit tracks and tags.
** Tourist -> Basic
	Any Adherent TUser can promote a user with its username, or invite them with their email

* Tracks
** Upload
	Any Basic+ User can upload a track. Once a track is uploaded, it is stored in filesystem and processed through music-metadata plugin. Metadata are stored in db along with the song path. They are returned to client with a one time key to edit them later.
** Duration / Integrity
	We cannot be sure the uploaded file will be playable as given in metadata. There aint no simple solution to do that. However any playback error should be logged so we can be able to intervene manually (remove track/demote user).

* Tags
** Should be reformatted with a caps 1st letter. They are unique
** Can be retrieved by any Basic+ TUser
** Can be created by any Basic+ TUser

* Scheduling
	TODO...
