# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 01:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0001_initial'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedshow',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jingle',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoplaylistindex',
            name='auto_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.AutoPlaylist'),
        ),
        migrations.AddField(
            model_name='autoplaylistindex',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Song'),
        ),
        migrations.AddField(
            model_name='autoplaylist',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoplaylist',
            name='songs',
            field=models.ManyToManyField(through='radio.AutoPlaylistIndex', to='upload.Song'),
        ),
    ]
