# Generated by Django 2.0.4 on 2018-04-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedshow',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jingle',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoplaylistindex',
            name='auto_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.AutoPlaylist'),
        ),
        migrations.AddField(
            model_name='autoplaylistindex',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Song'),
        ),
        migrations.AddField(
            model_name='autoplaylist',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoplaylist',
            name='songs',
            field=models.ManyToManyField(through='radio.AutoPlaylistIndex', to='radio.Song'),
        ),
    ]
