# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20171103_0735'),
        ('radio', '0002_auto_20171019_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DurationField(default=datetime.timedelta(0))),
                ('artist', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.FileUpload')),
            ],
        ),
        migrations.AlterField(
            model_name='autoplaylist',
            name='songs',
            field=models.ManyToManyField(through='radio.AutoPlaylistIndex', to='radio.Song'),
        ),
        migrations.AlterField(
            model_name='autoplaylistindex',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Song'),
        ),
    ]
