# Generated by Django 2.1.1 on 2018-10-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_livestream_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
