# Generated by Django 2.1.1 on 2019-02-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_auto_20181030_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
