# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0001_initial'),
        ('upload', '0002_auto_20171025_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.TaskResult'),
        ),
    ]
