# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 01:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='temp/%H%M%S/')),
                ('up_from', models.URLField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('up_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DurationField()),
                ('artist', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.FileUpload')),
            ],
        ),
    ]
