# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_fileupload_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='base_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='audio',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
    ]
